FROM python:3.9.13-alpine3.15
WORKDIR ../hello_docker
RUN ["pip","install","-r","requirements.txt"]
#ENV PYTHONDONTWRITEBYTECODE=1
#ENV PYTHONUNBUFFERED=1
#WORKDIR
#Learn more about the "WORKDIR" Dockerfile command.
# /code
#COPY
#Learn more about the "COPY" Dockerfile command.
# requirements.txt /code/
#COPY . /code/